### ISSUE TITLE
Write first draft of Random Error chapter

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/r4epi#106]
# Overview

**Fall 2023**

This content needs to come before we start calculating confidence intervals for anything. Given that the source of random error we focus on the most is sampling variability, perhaps it should come right after our discussion of populations. We can then immediately start calculating confidence intervals in the measures of occurrence chapter. This will also mean that we won't have learned any measures that we can use for examples in the random error chapter. So, we would just have to say something like, "don't worry about the measure for now. Just interpret the p-value and/or confidence interval." I don't think I like that. So, let's keep random error between measures of occurrence and measures of association. 

- I didn't have time to write this chapter. I assigned Modern Epidemiology chapter 15 instead. 
- My intent is to create a lab warm-up in PowerPoint that can serve as a foundation for the random error chapter in R4Epi.
- If I get that PowerPoint made this week, then I can start the chapter by moving that content over.
- This task is related to brad-cannell/epi_3_public#26

# Terms/concepts to include

- [ ] For each of the measures covered in measures of occurrence, show them how to calculate the confidence interval, p-value, and p-value curve for each measure. 
- [ ] What is random error? Chance vs. deterministic
- [ ] P-value curves (https://paperpile.com/app/p/9c5734e3-eace-4919-9300-f8c046bcdd5d)
- [ ] Sample size effect on p-values, confidence intervals, and p-value curves
- [ ] Simulate differential and non-differential misclassification using the methods in [Rudolph and Fox](https://paperpile.com/app/p/d038668a-e7f6-0461-be36-263ab32fdce0), example 2.

# Tasks

- [ ] Currently, the lab warm-up R code uses a regression model to demonstrate p-values, but we haven't yet covered the regression. I should probably come back and change this to some measure from measures of occurrence, which we have already measured.
