### ISSUE TITLE
Convert Intro to R Chapters to Quarto

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/r4epi#157]
# Overview

2024-05-21
- I finished moving over the introduction and front matter yesterday.
- Now, we need to move over all of the chapters we use for Intro to R to the Quarto version of R4Epi. We will treat the Epi III chapters as a separate task because they are generally less well-developed.
- I don't think we actually need the pictures at the beginning of the chapters, the main points at the top of the chapter, or the summary at the end of the chapter. I looked at several other books and most of them don't have these elements. Additionally, the Quarto book comes built-in with a table of contents, of and within, chapters.

## Converting R4Epi to Quarto 
- Create a new folder in chapters for each chapter. Name it the same thing as the chapter name.
- Move the .Rmd file over and change the file extension to .qmd.
- Move images and other media to the folder you created above.
- For each code chunk
  - Change the code chunk options to Quarto format. At least, it should have a `label` and `echo` option. **The find and replace tool can be helpful with all of these.**
    - Prefix the label with the chapter name. For example: `#| label: installing_r_and_rstudio_screenshot_cran`. 
    - After the chapter prefix, use the name of the media file being used in the code chunk, if applicable.
    - Set echo to false with: `#| echo: false`
    - Don't forget to remove the old code chunk options. For example: `{r screenshot-cran, echo=FALSE}`
  - Update the file paths for media files you moved over above.
- Look at the Planner board to see if changes need to be made to the chapter.
- Change some bolded words to [glossary](https://brad-cannell.github.io/test_quarto_book/chapters/cross_references/cross_references.html#glossary) entries.
- Remove images at the beginning of chapters, summaries at the end, etc., if they exist.
- Add the chapter to `_quarto.yml`.

## Useful links
- [R4Epi](https://www.r4epi.com/)
- [R4Epi Quarto Version](https://brad-cannell.github.io/r4epi_quarto/)
- [Test Quarto Book](https://brad-cannell.github.io/test_quarto_book/)
- [R4Epi Wiki](https://github.com/brad-cannell/r4epi/wiki)

# Tasks

- [ ] Installing R and RStudio
- [ ] What is R?
- [ ] Navigating the RStudio Interface
- [ ] Speaking R's Language
- [ ] Let's Get Programming
- [ ] Asking Questions
- [ ] R Scripts
- [ ] Quarto Files
- [ ] R Projects
- [ ] Coding Best Practices
- [ ] Using Pipes
- [ ] Introduction to Data Transfer
- [ ] File Paths
- [ ] Importing Plain Text Files
- [ ] Importing Binary Files
- [ ] RStudio's Data Import Tool
- [ ] Exporting Data
- [ ] Introduction to Descriptive Analysis
- [ ] Numerical Descriptions of Categorical Variables
- [ ] Measures of Central Tendency
- [ ] Measures of Dispersion
- [ ] Describing the Relationship Between a Continuous Outcome and a Continuous Predictor
- [ ] Describing the Relationship Between a Continuous Outcome and a Categorical Predictor
- [ ] Describing the Relationship Between a Categorical Outcome and a Categorical Predictor
- [ ] Introduction to Data Management
- [ ] Creating and Modifying Columns
- [ ] Subsetting Data Frames
- [ ] Working with Dates
- [ ] Working with Character Strings
- [ ] Conditional Operations
- [ ] Working with Multiple Data Frames
- [ ] Restructuring Data frames
- [ ] Introduction to Repeated Operations
- [ ] Writing Functions
- [ ] Column-wise Operations in dplyr
- [ ] Writing For Loops
- [ ] Using the purrr Package
- [ ] Introduction to git and GitHub
- [ ] Using git and GitHub

**Comment by bmbuchanan93** [comment]
@mbcann01 all of section 1 is ready to be reviewed!

**Comment by mbcann01** [comment]
Thank you!

**Comment by mbcann01** [comment]
@bmbuchanan93 I started reviewing the Navigating RStudio chapter today. Thank you for converting it over! You can see some of my notes in #163. 

I noticed that the chapter will need new screenshots. The appearance of RStudio has changed a little bit. For example, “jobs” now says “background jobs”. Additionally, RStudio doesn’t show the project you’re working on in the top right corner anymore. Do you think you'd be able to help me with that?

**Comment by bmbuchanan93** [comment]
@mbcann01 all of section two is ready for review!

**Comment by bmbuchanan93** [comment]
@mbcann01 I have been working on section 3. When I go to render I get the warning : "WARNING: chapters/contributing/contributing.html: Unable to resolve crossref @sec-quarto-files". I know that is for cross-references, but I cannot for the life of me find where the quarto file reference is.

**Comment by mbcann01** [comment]
@bmbuchanan93 Have you tried searching in the and files you created since the last render with the find tool?

**Comment by bmbuchanan93** [comment]
@mbcann01 Finally figured it out! Some chapters ready for review:

Introduction to data transfer
File Paths
Introduction to git and GitHub
Using git and GitHub

**Comment by bmbuchanan93** [comment]
@mbcann01  importint plain and binary text chapters are ready for review.

**Comment by mbcann01** [comment]
@bmbuchanan93 Thank you!

**Comment by edambo** [comment]
Notes

- [ ] In categorical_variables.qmd, on line 143, [later in the book](#creating-modifying-columns). The reference for the creating and modifying columns chapter needs to be updated when the chapter is created.

- [ ] In categorical_variables.qmd, line 345 should also be updated - [Using pipes].

- [ ] In the dplyr_column_wise.qmd file, on line 474,  the reference for the [chapter on restructuring data frames][Restructuring data frames] needs to be updated

The following glossary terms need to be reviewed:

- [ ] Bivariate
- [ ] Complete case analysis
- [ ] For loop
- [ ] Frequency count
- [ ] Iteratively
- [ ] Lexical scoping rules
- [ ] Marginal totals
- [ ] Mean 
- [ ] Median
- [ ] Mode
- [ ] Outcome variable
- [ ] Percentage
- [ ] Predictor variable
- [ ] Proportion
- [ ] Range
- [ ] Split-apply-combine
- [ ] Standard deviation
- [ ] Two-way frequency table
- [ ] Univariate
- [ ] Variance
- [ ]

**Comment by mbcann01** [comment]
# 2025-05-15 Brad and Rachit Meeting

- Rachit completed the initial conversion to Quarto for all chapters up to 39. Using Git and GitHub.

To do:

- [ ] Change file paths to image name only.
