### ISSUE TITLE
Turn measures of occurrence module into a chapter

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/r4epi#84]
# Overview

I want to add all the modules from the Fall 2022 Epidemiology III class to the epidemiology half of the book. 

The plan for right now is just to get the slides into Rmd format wholesale. I can make them better later.

## Left off

2023-09-05
Working on moving over the PP slides.
- Left off at slide 2 and line 127 of 03_measures_of_occurrence.
- Just get the PowerPoint slides moved over. Improve later.

## Tasks

- [x] Move usable parts of PowerPoint slides over to Rmd.
- [x] Create a first draft of this chapter.
- [x] Add to reading list.
- [ ] Post announcement
