### ISSUE TITLE
Clean up the wiki

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/r4epi#85]
# Overview

I'm trying to create a [wiki](https://github.com/brad-cannell/r4epi/issues/85#issue-1510410656) that will help me (and any other potential coauthors) create and revise content for the book in a more efficient and consistent way. 

On 2022-12-14, I moved over a lot of the content from two Google Docs that were sort of serving the same purpose ([R for Epidemiology Textbook Notes](https://docs.google.com/document/d/1JKRUx_4jqT2jdIrLL1t9HxgtGBNlX0LDUThhKXlosw4/edit#heading=h.3mzojahhaxxq) and [📚Textbook](https://docs.google.com/document/d/1x0IH7WP7jI1HnqpRhvG07EwlMWdt4Yxq5TVJONDN-1Q/edit)). However, it needs a lot of cleaning up. Some of the content is outdated, so notes were just quickly jotted down, and the organization isn't good.

## Task list

- [x] Figure out the nuts and bolts of building the wiki (#82, #78, #79)
- [x] Complete first draft of formatting page
- [x] Complete first draft of ideas page
- [x] Complete first draft of references page

## Left off at...

I was working on this and then jumped into #82
