### ISSUE TITLE
Move over front matter to Quarto

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/r4epi#96]
# Overview

Move over the front matter from [index.Rmd](https://github.com/brad-cannell/r4epi/blob/master/index.Rmd) to this repository.

Although it isn't directly related to moving over index, there are a number of issues in the [R4Epi project](https://github.com/orgs/brad-cannell/projects/3) related to the functionality of Quarto. We should probably get those knocked out before 
- [x] Update structure page in Wiki.
- [x] Add [formatting guidance](https://uthtmc.sharepoint.com/:w:/r/sites/SPHDallasShared/_layouts/15/Doc.aspx?sourcedoc=%7BC127E988-ABFA-4FED-A433-C1E7DE78C4A0%7D&file=Style%20Guide.docx&action=default&mobileredirect=true) to the formatting page in the wiki.
- [x] [Add font awesome graphics to wiki](https://github.com/brad-cannell/r4epi/issues/79)
- [x] [Add TOC to the top of wiki pages](https://github.com/brad-cannell/r4epi/issues/78)
- [x] Add "Top" throughout
- [x] [Clean up the wiki](https://github.com/brad-cannell/r4epi/issues/85)
- [x] Add instructions for adding hyperlinked keywords to the glossary (#97)

# Tasks

- [x] Create a glossary, add hyperlinked keywords, and maybe a note to NOTES (#97)
- [x] Add reference page
- [x] Finish moving over the rest of the content for the `contributing` chapter
  - [x] Revise the text
  - [x] Republish so that we can get accurate screenshots
  - [x] Update screenshots as needed
  - [x] Move over the `Issues` section
- [x] Move over the `License information` section
- [x] Move over the `About the authors` page

**Comment by mbcann01** [comment]
2023-12-15
- Finished the Wiki and the other general Quarto list above.
- Finished the pull request section of the contributing chapter.
- Pick up with the `Issues` section next.

**Comment by mbcann01** [comment]
2024-05-21

- Finished almost everything.
- Trying to figure out why the font awesome icons don't work on the `About the Authors` page.
