### ISSUE TITLE
Create a cross-referenced glossary

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/r4epi#97]
# Overview

- I was working on moving the front matter from the original bookdown Rmd documents to the new qmd documents (#96). 
- As I was doing so, I decided it would be a good time to double-check and enforce our [conventions for emphasizing text](https://github.com/brad-cannell/r4epi/wiki/Emphasizing-Text). 
- That led me to notice that a bolded word in `contributing.qmd` should really be hyperlinked to the glossary.
- That led me to try to figure out how to make that happen.

I don't think we can link random words in the glossary. However, I think we may be able to make the glossary words headers, style them with CSS, then link words in the chapters to those headers in the glossary. 

## Useful links

- [Quarto cross-reference documentation](https://quarto.org/docs/books/book-crossrefs.html)
- [Cross-referencing chapter of test Quarto book](https://brad-cannell.github.io/test_quarto_book/chapters/cross_references/cross_references.html)

# Left off at

2023-07-19: I think this is working now, thanks to [this SO post](https://stackoverflow.com/questions/76691907/quarto-link-a-word-in-one-qmd-document-to-a-word-in-a-different-qmd-document/76719362#76719362).

# Tasks

- [x] Get cross-references to work in cross_references.qmd of test quarto book.
- [x] Link at least one word to the glossary in the test quarto book. 
- [x] Figure out how to link to words in the glossary without them showing up in the PDF table of contents.
